### ISSUE TITLE
Seed is irrelevant

### ISSUE THREAD

**Issue by Efreak** [sammcj/superprompter#7]
This produces the same output regardless of what I set the seed to. I looked around online and found a suggestion to add `random.seed(seed)` the same as torch. This doesn't work. What does work appears to be setting N and P to something other than 1. I also had to increase the repetition penalty and one of the other parameters.

**Comment by Efreak** [comment]
Also, torchaudio and torchvision aren't needed here.

**Comment by sammcj** [comment]
Hopefully fixed this along with a few other tweaks in a change I push merged.
I'll upload a built artefact for macOS with the release shortly.

Please do re-open if these changes don't fix it!

**Comment by Efreak** [comment]
Regarding build artifacts: a single-file exe produced by pyinstaller works fine on Windows and can probably be made by a GitHub action. I tried making a pyoxidizer (which seems technically superior) but didn't feel like looking at the settings (laziness. Pyinstaller needs 3 parameters. Pyoxidizer has an entire config).
